name: Build

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

env:
  CONVERTER_NAME: gltf_image_converter
  PLUGIN_NAME: gltf_supercell_io

permissions:
  contents: write

jobs:
  build-plugin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Get release version from tag
        run: |
          echo "VERSION=${GITHUB_REF#refs/*/v}" >> $GITHUB_ENV

      - name: Build plugin zip (wheels generated at build time)
        run: |
          ./scripts/build.py build ${{env.VERSION}}

      - name: Create GitHub Release and Upload Files
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          name: ${{ github.event.repository.name }}-${{ env.VERSION }}
          files: dist/*.zip
          generate_release_notes: true
